name: Matrix Demo

on: [push, workflow_dispatch]

jobs:
  build:
    continue-on-error: true

    runs-on: ${{matrix.operating-system}}

    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exlude:
          - node-version: 12
            operating-system: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build

  deploy:
    uses: ./.github/workflows/reusable.yml
